### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tillkruss** [atom/ide-php#63] opened 2017-10-17 19:57 UTC
I'm seeing the following error when viewing the outline on a PHP file:

```
/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:187 TypeError: Cannot read property 'length' of undefined
    at r.push.outline.tokenizedText.map (/Users/Till/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineView.js:342:28)
    at Array.map (native)
    at renderItem (/Users/Till/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineView.js:340:37)
    at OutlineTree.render (/Users/Till/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineView.js:297:25)
    at k (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:147:346)
    at beginWork (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:150:341)
    at e (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:182:356)
    at k (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:183:362)
    at p (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:184:367)
    at y (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:188:412)
    at D (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:187:423)
    at Object.enqueueSetState (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:140:182)
    at OutlineView.v.setState (/Users/Till/.atom/packages/atom-ide-ui/node_modules/react/cjs/react.production.min.js:12:357)
    at a.subscription.default.props.outlines.subscribe.outline [as _next] (/Users/Till/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineView.js:110:12)
    at a.__tryOrUnsub (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240:110)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240:110)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:294)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:68)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:68)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at p (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:36)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:65:41)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._subscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:59:420)
    at a.b._trySubscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45:318)
    at a.b.subscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45:144)
    at b.call (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:64:293)
    at b.subscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45:113)
    at p (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:77)
    at a._callFactory (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66:325)
    at a.tryDefer (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66:215)
    at new a (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66:156)
    at a._subscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66:43)
    at a.b._trySubscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45:318)
    at a.b.subscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45:144)
    at b.call (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:105:492)
    at b.subscribe (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45:113)
    at p (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:77)
    at a._innerSub (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239:187)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239:51)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48:322)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:116:518)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240:110)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:68)
    at a._next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69:274
x @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:187
p @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:184
y @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:188
D @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:187
enqueueSetState @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:140
v.setState @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/react/cjs/react.production.min.js:12
subscription.default.props.outlines.subscribe.outline @ /Users/Till/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineVie…:110
a.__tryOrUnsub @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
p @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:65
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._subscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:59
b._trySubscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
b.subscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
b.call @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:64
b.subscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
p @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23
a._callFactory @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
a.tryDefer @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
a @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
a._subscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
b._trySubscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
b.subscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
b.call @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:105
b.subscribe @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
p @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23
a._innerSub @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:116
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
(anonymous) @ /Users/Till/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69
```

My plugins:
```
├── atom-ide-ui@0.5.1
├── busy-signal@1.4.3
├── docblockr@0.11.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.13
├── go-debug@1.5.2 (disabled)
├── go-plus@5.5.6 (disabled)
├── go-signature-statusbar@1.2.3 (disabled)
├── ide-css@0.2.0
├── ide-html@0.3.0
├── ide-php@0.6.9
├── ide-vue@0.1.7
├── intentions@1.1.5
├── language-api-blueprint@1.0.2 (disabled)
├── language-blade@0.36.0
├── language-docker@1.1.8
├── language-dotenv@1.1.1
├── language-gherkin@1.0.4
├── language-markdown@0.25.1
├── language-nginx@0.8.0 (disabled)
├── language-patch@1.2.0
├── language-scala@1.1.9 (disabled)
├── language-swift@0.5.0 (disabled)
├── language-vue@0.23.1
├── linter@2.2.0 (disabled)
├── linter-eslint@8.3.2
├── linter-htmlhint@1.3.4
├── linter-jsonlint@1.3.0 (disabled)
├── linter-phpmd@2.0.0
├── linter-scss-lint@3.1.1
├── multi-cursor@2.1.5
├── php-cs-fixer@4.1.1
├── pigments@0.40.2
├── project-manager@3.3.5
├── svg-preview@0.11.0
├── tester@1.4.0
└── tester-phpunit@1.0.6
```

**Comment by rsese** [comment] 2017-10-27 21:01
Thanks for the report @tillkruss - just to confirm, what version of macOS are you on?  Also, what version of ide-php are you running?

Lastly, can you reproduce with any PHP file or just a particular file?

**Comment by rsese** [comment] 2017-11-01 06:41
Hmmm, I'm unable to reproduce problems with the outline view with simple PHP files as I commented in another issue /cc https://github.com/atom/ide-php/issues/22#issuecomment-340998294.  

With this simple file, can you trigger the error?

```php
<?php
function foo() {
  echo "<p>Hello World!</p>";
}
?>

<html>
 <head>
  <title>Hello World</title>
 </head>
 <body>
 <? foo(); ?>
 </body>
</html>
```

**Comment by tillkruss** [comment] 2017-11-04 00:32
Yes, same error with that simple file.

```
TypeError: Cannot read property 'length' of undefined
    at r.push.outline.tokenizedText.map (/Users/Till/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineView.js:350:28)
    at Array.map (native)
```

**Comment by tillkruss** [comment] 2017-11-09 00:30
Is there any way to reset the plugin somehow?

**Comment by rsese** [comment] 2017-11-14 06:59
From devtools Console, can you enable debugging by running `atom.config.set('core.debugLSP', true)` and share the output when you try to enable the outline view?  I don't think there's really anyway to reset ide-php, you could always uninstall/reinstall I guess.

Also how did you install PHP?  I installed via homebrew.

**Comment by tillkruss** [comment] 2017-11-14 20:11
Thanks! Here is the log: https://paste.ee/p/Le5fl

I've installed PHP 7.1.10 using Home-brew. Works like a charm.

**Comment by damieng** [comment] 2017-11-16 00:03
@tillkruss Are you saying the error is now gone once you upgraded php?

**Comment by tillkruss** [comment] 2017-11-16 03:21
No, sorry, that was unclear, you're right.

I've installed PHP using Homebrew and PHP works flawless, but Atom PHP IDE does not.

**Comment by rsese** [comment] 2017-11-28 09:09
Thanks for confirming - can you share the log output when you get the error with that simple PHP file I shared [above](https://github.com/atom/ide-php/issues/63#issuecomment-341003581)?

**Comment by tillkruss** [comment] 2017-11-28 15:56
Sure, here: https://paste.ee/p/s4tE1

**Comment by tillkruss** [comment] 2018-02-21 17:51
I'm still seeing this error. Any help would be appreciated.

<img width="2553" alt="screen shot 2018-02-21 at 9 50 41 am" src="https://user-images.githubusercontent.com/665029/36496327-c648f090-16ec-11e8-9a96-966f936832c0.png">

**Comment by rsese** [comment] 2018-02-23 00:28
Sorry you're still having trouble with this @tillkruss - not sure what the issue could be since we can't repro it and it doesn't seem like anyone else has reported hitting this error.

Can you try temporarily resetting to factory defaults (https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) and then try installing just `atom-ide-ui` and `ide-php` and see if that makes a difference?

**Comment by tillkruss** [comment] 2018-02-23 16:48
Yeah, that worked. I'll see if I can isolate what other package caused that issue.

**Comment by tillkruss** [comment] 2018-02-23 19:03
@rsese: It's the IDE-HTML package that breaks it: https://atom.io/packages/ide-html

**Comment by damieng** [comment] 2018-02-23 19:19
It looks like ide-html is returning bad outlines.  That will have to be fixed over on their repo.

**Comment by tillkruss** [comment] 2018-02-23 21:35
Could one of you open an issue on their repo? I don't understand the issue.

**Comment by rsese** [comment] 2018-02-24 01:04
https://github.com/liuderchi/ide-html/issues/21 if you want to subscribe @tillkruss 

We'll go ahead and close this issue since the error was coming from ide-html.

Thanks again for reporting @tillkruss :v:

**Closed by rsese** 2018-02-24 01:04 UTC
Labels: more-information-needed

**Comment by tillkruss** [comment] 2018-02-24 01:08
Thanks!
