### ISSUE TITLE
Anoying autocomplete outside <?php ?> tag

### ISSUE THREAD

**Issue by Jensen0710** [atom/ide-php#96] opened 2018-01-06 14:18 UTC
Every time i'm working with HTML the <?php autocomplete tag from ide-php pops up as the number 1. snippet, which is annoying as f*uck. I can't  seem to get rid of it.
Even if i make another snippet, it still comes 2nd
<img width="377" alt="screen shot 2018-01-06 at 15 12 23" src="https://user-images.githubusercontent.com/9888000/34640560-d1097d36-f2f4-11e7-82ea-4bae88fb632e.png">

**Comment by vinkla** [comment] 2018-01-06 14:54
Duplicate of #47

**Comment by 50Wliu** [comment] 2018-01-06 22:16
Thanks @vinkla.

**Closed by 50Wliu** 2018-01-06 22:16 UTC
