### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by AlexPsilon** [atom/ide-php#23] opened 2017-09-14 09:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.6.2

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 1

```
At file:///usr/share/atom-beta/resources/app.asar/static/index.html:2

SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at StreamMessageReader.onData (/packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:210:29)
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -0:49.5.0 core:backspace (input.hidden-input)
  2x -0:49 core:move-right (input.hidden-input)
     -0:48.4.0 core:move-left (input.hidden-input)
     -0:46.3.0 core:backspace (input.hidden-input)
     -0:41.5.0 core:move-left (input.hidden-input)
  5x -0:35.6.0 core:backspace (input.hidden-input)
     -0:33.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:33.7.0 snippets:expand (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
  2x -0:27.1.0 core:move-down (input.hidden-input)
     -0:26.6.0 core:move-up (input.hidden-input)
     -0:19.6.0 editor:newline (input.hidden-input)
     -0:19.4.0 core:move-up (input.hidden-input)
     -0:17.4.0 editor:newline (input.hidden-input)
     -0:15.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:12.5.0 core:move-right (input.hidden-input)
  2x -0:11.8.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-ide-ui 0.3.1 
autocomplete-modules 1.7.0 
busy-signal 1.4.3 
calc 0.4.0 
color-picker 2.2.5 
editorconfig 2.2.2 
es6-snippets 0.3.0 
git-control 0.9.0 
git-plus 7.9.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ide-flowtype 0.17.4 
ide-php 0.6.2 
ide-typescript 0.6.1 
ide-vue 0.1.3 
intentions 1.1.5 
language-babel 2.74.2 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.2.1 
linter-php 1.4.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.6.0 
prettier-atom 0.38.0 
project-manager 3.3.5 
seti-icons 1.5.4 
```

**Comment by rsese** [comment] 2017-09-14 20:43
Thanks for the report! Can you confirm if the error is reproducible and if so, what are the steps to reproduce?

**Comment by rsese** [comment] 2017-09-14 20:45
Oh just saw https://github.com/atom/ide-typescript/issues/26, looks the same?

I'll close as a duplicate of https://github.com/atom/ide-typescript/issues/26 for now but if you can share any steps to reproduce @AlexPsilon that would be helpful.

**Closed by rsese** 2017-09-14 20:45 UTC
