### ISSUE TITLE
Atom always recommend me <?php

### ISSUE THREAD

**Issue by Kayoshi-dev** [atom/ide-php#99] opened 2018-01-31 10:15 UTC
Hello, I don't know if I should put this here but,
I recently installed atom-ide and ide-php, and now, when I'm writing my code, it always recommend me the <?php tag.
![ok](https://user-images.githubusercontent.com/28494879/35617269-0449fa22-0678-11e8-9e36-aa7fce314261.png)

Is there a way to disable only this tag recommendation or smth like that?

Thanks!

**Comment by vinkla** [comment] 2018-01-31 11:49
Duplicate of #47

**Closed** 2018-01-31 15:11 UTC
