### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by youngjuning** [atom/ide-php#65] opened 2017-10-25 07:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.6.9

### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\10037\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:606

Error: Connection is closed.
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didCloseTextDocument (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:137:10)
    at TextEditorSyncAdapter.didClose (/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:266:22)
    at wrapped (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:661:26)
    at TextEditor.module.exports.Model.destroy (~/AppData/Local/atom/app-1.21.1/resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.21.1/resources/app/src/pane.js:708:24)
    at TabBarView.module.exports.TabBarView.closeTab (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
     -6:53.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -3:41.6.0 core:confirm (input.hidden-input)
  5x -0:38.6.0 core:backspace (input.hidden-input)
     -0:35.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
api-docs 0.0.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-hexo 1.1.1 
atom-ide-ui 0.5.2 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atom-miku 2.2.5 
atom-minify 0.8.0 
atom-ternjs 0.18.3 
autocomplete-json 5.5.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
caniuse 0.9.2 
color-picker 2.2.5 
copy-path 0.4.2 
css-snippets 1.1.0 
custom-title 1.0.1 
docblockr 0.11.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
fonts 3.0.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-css 0.2.0 
ide-html 0.3.0 
ide-php 0.6.9 
ide-typescript 0.6.2 
insert-timestamp 0.2.4 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-apache 1.7.0 
language-ejs 0.4.0 
language-html-swig 2.0.1 
language-markdown 0.25.1 
language-stylus 0.2.0 
less-autocompile 1.0.0 
linter-eslint 8.4.0 
linter-jshint 3.1.6 
linter-stylelint 4.0.2 
linter-tidy 2.3.1 
markdown-preview-enhanced 0.14.11 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.6.4 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-codeglance 0.4.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
one-dark-material-syntax 1.0.3 
open-file 1.4.0 
open-in-browsers 0.0.30 
pangu 0.5.0 
pdf-view 0.59.0 
php-cs-fixer 4.1.1 
php-server 0.8.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
preview-inline 1.4.7 
regex-railroad-diagram 0.19.4 
Remote-FTP 1.2.6 
simple-drag-drop-text 0.3.6 
simplified-chinese-menu 5.3.4 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
toggle-quotes 1.0.1 
toggler 0.3.0 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.3.0 
wordpress-api 1.2.2 
zip-folder 3.2.0 
```

**Comment by damieng** [comment] 2017-10-25 08:10
Duplicate of #60

**Closed by damieng** 2017-10-25 08:10 UTC
