### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by umpirsky** [atom/ide-php#21] opened 2017-09-13 20:01 UTC
[Enter steps to reproduce:]

1. Search for text in folder
2. Click one of results to open php file

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.6.1

### Stack Trace

Uncaught Error: Connection is closed.

```
At /home/umpirsky/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604

Error: Connection is closed.
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:124:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /usr/share/atom-beta/resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/display-layer.js:823:24)
    at decorationLayerDisposable.textDecorationLayer.onDidInvalidateRange (/usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/display-layer.js:161:20)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom-beta/resources/app/src/tokenized-buffer.js:241:28)
    at /usr/share/atom-beta/resources/app/src/tokenized-buffer.js:206:32
    at /usr/share/atom-beta/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -0:32 core:paste (input.hidden-input)
     -0:28 project-find:show (input.hidden-input)
     -0:27.7.0 core:paste (input.hidden-input)
  3x -0:26.6.0 core:confirm (input.hidden-input)
     -0:21.9.0 editor:consolidate-selections (input.hidden-input)
     -0:21.9.0 core:cancel (input.hidden-input)
     -0:17.3.0 intentions:highlight (input.hidden-input)
     -0:17.1.0 find-and-replace:show (input.hidden-input)
     -0:15.5.0 project-find:show (input.hidden-input)
     -0:15 core:confirm (input.hidden-input)
  2x -0:11.4.0 core:move-down (div.results-view.focusable-panel)
     -0:08.5.0 core:confirm (div.results-view.focusable-panel)
     -0:07.5.0 core:cancel (div.results-view.focusable-panel)
     -0:06.7.0 core:move-down (div.results-view.focusable-panel)
     -0:06.3.0 core:move-up (div.results-view.focusable-panel)
     -0:06.0 core:confirm (div.results-view.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.3.1 
busy-signal 1.4.3 
change-case 0.6.5 
docblockr 0.11.0 
firacode 0.3.0 
hyperclick 0.0.0 
ide-php 0.6.1 
intentions 1.1.5 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-jshint 3.1.5 
linter-php 1.4.0 
linter-ui-default 1.6.8 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-twig 4.0.0 
project-manager 3.3.5 
```

**Comment by mikebronner** [comment] 2017-09-13 23:06
This issue has become so prevalent for me all of a sudden, that I actually can't write any PHP code anymore (the error pops up and my keystrokes are no longer recognized in the editor). Any suggestions on package conflicts? Here's my error report:

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.6.1


### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/mike/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604

Error: Connection is closed.
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:124:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:823:24)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:757:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:756:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:739:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:946:22)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:897:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1631:28)
```

### Commands

```
     -2:15.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -1:55 core:save (input.hidden-input)
     -1:50.5.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
close-on-left 0.9.2 
file-icons 2.1.11 
ide-json 0.1.0 
ide-php 0.6.1 
ide-typescript 0.6.1 
ide-vue 0.1.3 
language-blade 0.34.0 
platformio-ide-terminal 2.6.0 
sync-settings 0.8.3 
zentabs 0.8.8 
```

**Comment by jbrooksuk** [comment] 2017-09-14 12:27
This *just* happened when I tried to add a PHP 7.0 function return type when typing the `:` character.

**Comment by jbrooksuk** [comment] 2017-09-14 12:27
And now I can't type anything 😫

**Comment by bad-mushroom** [comment] 2017-09-14 13:40
Been happening to me several times a day - can't seem to mail it down to what exactly triggers it. Seems i'll go to type something, and 💥 .

Atom 1.20.0 x64
`/Users/chris/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604`

**Stack Trace**
```
Error: Connection is closed.
    at new ConnectionError (/Users/chris/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/Users/chris/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/Users/chris/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/Users/chris/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didChangeTextDocument (/Users/chris/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:124:10)
    at TextEditorSyncAdapter.sendFullChanges (/Users/chris/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:823:24)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:757:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:756:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:739:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:946:22)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:897:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1651:28)
```

**Comment by ShaunaGordon** [comment] 2017-09-14 22:07
I'm getting the same issue, with what appears to be the same stack trace on OSX Sierra 10.12.6 with a fresh install of Atom 1.21.0-beta0 and atom-ide-ui and ide-php installed besides the core stuff.

As a bit of a workaround, a full Atom restart isn't necessary. You can just go into settings and disable/enable the ide-php package.

**Comment by avinash-mishra** [comment] 2017-09-15 04:36
Same issue.

**Comment by damieng** [comment] 2017-09-17 14:57
This happens if the server stops unexpectedly.

The latest ide-php package update - 0.6.6 - now reports an error dialog when this happens including any messages from the stderr on the language server.  That will better let us diagnose the crashes.

I'm going to close this issue so that we'll get more information the next time it happens (and there may be multiple error messages coming out that might need individual issues to address)

**Closed by damieng** 2017-09-17 14:57 UTC

**Comment by jbrooksuk** [comment] 2017-09-18 11:56
I had this issue, here is the output.

```
/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604 Uncaught Error: Connection is closed.
    at new ConnectionError (/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/Users/james.brooks/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didChangeWatchedFiles (/Users/james.brooks/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:136:10)
    at ServerManager.projectFilesChanged (/Users/james.brooks/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:262:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/project.js:297:40
    at PathWatcher.onNativeEvents (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:177:15)
/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604 Uncaught Error: Connection is closed.
    at new ConnectionError (/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/Users/james.brooks/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/Users/james.brooks/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didCloseTextDocument (/Users/james.brooks/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:128:10)
    at TextEditorSyncAdapter.didClose (/Users/james.brooks/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:266:22)
    at wrapped (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:661:26)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom Beta.app/Contents/Resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:708:24)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

**Comment by UziTech** [comment] 2017-09-18 16:12
I'm not seeing an error dialog when this happens. Just this error message with a stack trace.

```
Error: Connection is closed.
    at new ConnectionError (C:\Users\tjbrix\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:129:28)
    at throwIfClosedOrDisposed (C:\Users\tjbrix\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:604:19)
    at Object.sendNotification (C:\Users\tjbrix\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:658:13)
    at LanguageClientConnection._sendNotification (C:\Users\tjbrix\.atom\packages\ide-php\node_modules\atom-languageclient\build\lib\languageclient.js:231:15)
    at LanguageClientConnection.didChangeWatchedFiles (C:\Users\tjbrix\.atom\packages\ide-php\node_modules\atom-languageclient\build\lib\languageclient.js:136:10)
    at ServerManager.projectFilesChanged (C:\Users\tjbrix\.atom\packages\ide-php\node_modules\atom-languageclient\build\lib\server-manager.js:257:33)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\project.js:297:40
    at PathWatcher.onNativeEvents (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\path-watcher.js:671:15)
    at C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at NativeWatcher.onEvents (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\path-watcher.js:448:26)
    at handler (C:\Users\tjbrix\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\path-watcher.js:177:15)
```

**Comment by damieng** [comment] 2017-09-18 16:16
@UziTech and @jbrooksuk when this happens can you look in the dev tools window for the line that says starting ... (pid x)

x will be a number that is basically the background process.  If you can open up Task Manager (Windows) or Activity Viewer (Mac) and see if that process id is still running after the "connection is closed" message.

**Comment by UziTech** [comment] 2017-09-18 16:27
The server is still running. when I stop the server I get this error:

![image](https://user-images.githubusercontent.com/97994/30552577-1355fc56-9c64-11e7-9388-3b45a825b417.png)

It seems the same thing is happening with ide-typescript https://github.com/atom/ide-typescript/issues/17

**Comment by UziTech** [comment] 2017-09-18 18:53
seems odd but i think disabling `ide-typescript` fixed the issue with `ide-php` failing when typing

**Comment by danjdewhurst** [comment] 2017-09-18 19:44
I don't have `ide-typescript` installed, however I do get this issue with `ide-php`.

It seems to be when I type `->with();`

**For example:**
```
return redirect(route('news'))
            ->with();
```

**Comment by zugoripls** [comment] 2017-09-20 05:31
same issue.

**Comment by berosoboy** [comment] 2017-09-23 17:46
I reach to this issue after stopping the php process manually, because it was using much CPU (80~90%)

**Comment by Danw33** [comment] 2017-10-02 12:28
Same issue here - A few seconds to a few minutes after opening projects that use PHP 7.1 specific features (class constant visibility, nullable types, void functions, etc.). When the error occurs any non-PHP tabs are fine, but PHP tabs cannot be typed into (pressing any key causes an additional error dialogue to appear).

- macOS High Sierra 10.13 on MacBookPro14,3
- Atom 1.21.0-beta2 x64
- atom-ide-ui 0.4.0
- ide-php 0.6.9

<img width="488" alt="screen shot 2017-10-02 at 13 11 24" src="https://user-images.githubusercontent.com/5680603/31076660-3c49bcdc-a773-11e7-9eb3-55300ff8fd32.png">

Devtools:

<img width="1649" alt="screen shot 2017-10-02 at 13 12 36" src="https://user-images.githubusercontent.com/5680603/31076716-789ee0f4-a773-11e7-8893-cead8e71298d.png">
(Last error is then repeated several times)

Not sure if I can provide anything else to help pin this down?

**Comment by martinbean** [comment] 2017-10-10 08:59
This is still happening for me, after having Atom open only a few minutes. This is what’s in Console:

```
Uncaught Error: Connection is closed.
    at new ConnectionError (/Users/martin/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/Users/martin/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/Users/martin/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/Users/martin/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didChangeWatchedFiles (/Users/martin/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:145:10)
    at ServerManager.projectFilesChanged (/Users/martin/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:262:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:297:40
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

I also don’t know if it’s related, but I find autocomplete and tab-completions are _very_ laggy when I enable this package too.

**Comment by djouuuuh** [comment] 2017-10-19 14:33
Has this been solved? I'm still having this issue...

**Comment by damieng** [comment] 2017-10-19 14:37
No, it hasn't been solved as we don't have a repro. It was closed in the hope we'd get some new issues opened with relevant information but that hasn't happened.

**Comment by UziTech** [comment] 2017-10-19 15:33
I'm still getting this issue When I have ide-php and ide-typescript enabled at the same time. If one or the other is disabled the problem goes away.

[Enter steps to reproduce:]

1. Enable `ide-typescript` when `ide-php` is already enabled
2. Restart Atom
3. Type in a *.js file

**Atom**: 1.22.0-beta1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\tjbrix\Documents\GitHub\ide-php\node_modules\vscode-jsonrpc\lib\main.js:606

Error: Connection is closed.
    at new ConnectionError (~/Documents/GitHub/ide-php/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (~/Documents/GitHub/ide-php/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (~/Documents/GitHub/ide-php/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (~/Documents/GitHub/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didChangeTextDocument (~/Documents/GitHub/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:133:10)
    at TextEditorSyncAdapter.sendFullChanges (~/Documents/GitHub/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:641:38
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/text-buffer/lib/display-layer.js:825:24)
    at ~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/text-buffer/lib/text-buffer.js:780:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/text-buffer/lib/text-buffer.js:779:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/text-buffer/lib/text-buffer.js:762:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1001:22)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/text-buffer/lib/text-buffer.js:955:20)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:1687:32)
    at ~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:1248:30
    at TextEditor.module.exports.TextEditor.mergeSelections (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:2635:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:2597:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:1246:25)
    at TextEditor.module.exports.TextEditor.insertText (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor.js:1212:25)
    at TextEditor.object.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.22.0-beta1/resources/app/src/text-editor-component.js:1630:30)
```

**Comment by UziTech** [comment] 2017-10-19 15:36
The weird thing is that error stack lists the error coming from `ide-php` but it was from typing in a *.js file

~/Documents/GitHub/**ide-php**/node_modules/vscode-jsonrpc/lib/main.js:131:28

**Comment by Danw33** [comment] 2017-10-19 15:44
@damieng I can reproduce this repeatedly when editing php files in a large project, is there anything I can provide to help?
