### ISSUE TITLE
Snippets are slow after activating ide-php

### ISSUE THREAD

**Issue by mehdibo** [atom/ide-php#77] opened 2017-11-20 00:14 UTC
When I activate ide-php snippets take time to show,
Before activating ide-php:
I type `if`, a menu appears instantly with options (if, if?, ifelse..)

After activating ide-php:
I type `if`, but the menu takes a while until it shows up, but when I hit tab
it outputs the snippet normally

**Comment by rsese** [comment] 2017-11-21 18:58
Thanks for the report - I think this is a duplicate of https://github.com/atom/ide-php/issues/10 so you can subscribe there for updates if you'd like.  If I mis-understood anything please let me know :v:

**Closed by rsese** 2017-11-21 18:58 UTC
