### ISSUE TITLE
Autocomplete does not include arguments

### ISSUE THREAD

**Issue by andrews05** [atom/ide-php#67] opened 2017-11-01 19:24 UTC
Would be great if the autocomplete could include the function parameters when activated. Currently it completes the function name only.

**Comment by damieng** [comment] 2017-11-01 20:26
Done! Thanks.

**Comment by damieng** [comment] 2017-11-01 20:27
We have the code signature stuff now available in the atom-ide-ui package and atom-languageclient, just need to see if the language server supports this. If it does it should just be adding the service to the package.json

**Comment by JasonTheAdams** [comment] 2017-11-07 18:21
Yes! I thought at first the IDE wasn't working properly as I assumed arguments and such would be included. Seems like a necessary feature for an IDE. Hope to see this introduced in the future!

**Comment by damieng** [comment] 2017-11-07 18:38
It turns out the underlying language server doesn't yet support signature help, it's being tracked at https://github.com/felixfbecker/php-language-server/issues/18

**Comment by andrews05** [comment] 2017-11-20 05:33
Thanks for investigating this. In the meantime, is it possible to disable autocomplete for ide-php? I'm trying out php-integrator's autocomplete instead but I don't want ide-php suggestions showing as well (but I don't want to disable ide-php completely either).

**Comment by pixelarbeit** [comment] 2017-12-11 14:57
Is there an update on this? Apparently the language server supports signature help now.

**Comment by pixelarbeit** [comment] 2017-12-12 07:17
Thanks @rsese. I didn't have to. It was merged and released just after your answer.

**Comment by 50Wliu** [comment] 2017-12-12 17:50
@vinkla can you confirm if this is fixed after #86?

**Comment by damieng** [comment] 2017-12-12 18:00
Confirmed working here 
![image](https://user-images.githubusercontent.com/118951/33900443-3fa79b5a-df23-11e7-9313-b6379e594ad4.png)

**Closed by damieng** 2017-12-12 18:00 UTC
Labels: enhancement

**Comment by andrews05** [comment] 2017-12-13 08:24
Thanks heaps, the signature help is great :)
Two problems I've encountered with it though:
1. The help is always positioned above the line you're working on, which is a problem if you're at the top of the screen. IMO, it would be preferable to default to below the line and only move above if you're at the bottom of the screen.
2. I'm seeing `<p>` tags in the help for built-in functions like `substr`.

Lastly, what I was actually hoping for originally was to show the function parameters in the autocomplete suggestions, as I've seen in php-integrator. Would this be possible?
![autocomplete](https://user-images.githubusercontent.com/4584038/33928734-d3839742-e04b-11e7-8033-3864035dfd87.png)

**Comment by damieng** [comment] 2017-12-13 15:29
1. This would need to be reported on the atom-ide-ui package as that is where the underlying datatip code exists.

2. The help should either be ascii or markdown according to the protocol specification https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_signatureHelp  The language server must be returning HTML which will need to be fixed upstream there https://github.com/felixfbecker/php-language-server

3. I'm not sure why the language server doesn't return such data for autocomplete.  It might be due to performance in which case they could add it to resolve so it shows as you move the mouse up/down the list.  Either way they'll need to fix it upstream too

**Comment by andrews05** [comment] 2017-12-14 00:40
2. Hm, I've just tried it in VS Code and the `<p>` tags aren't showing there. I note the spec you link to says "A client could decide to remove HTML from the markdown", implying that it's not incorrect to have HTML in the markdown. If you're sure though, I'm happy to file an issue on the language server.

3. Tried this in VS Code as well and it appears to work exactly as you suggest, resolving only the highlighted item. So not sure that it is an issue with the language server?

**Comment by damieng** [comment] 2017-12-14 00:47
2. This is an on-going issue where people haven't coded to the formal written spec but have just done whatever VS Code seems to accept. That's a cat and mouse game that is time consuming to play.

3. I'd have to check that out then and I've exceeded the time I have available for ide-php right now (this project is disproportionally time consuming compared to the other ide-x packages).  Turning on debugging with `atom.config.get('core.debugLSP', true)` might shed light on it.

**Comment by andrews05** [comment] 2017-12-14 00:49
Okay, thanks for your help :)

**Comment by trymeouteh** [comment] 2018-03-20 03:25
I cannot seem to get the arguements to show up when I type a function. I have installed ide-php a few days ago and I have set the PHP Path.
